Repository goorm-369/893-front, pull requests merged in 2025-06, with the labels that each got.

#142 fix: style UI 개선 및 스타일 수정 - 버튼 크기 및 폰트 조정, 모달 크기 변경
  src/components/registration/AuctionStartTimeButton.tsx
  src/components/registration/AuctionTimeButton.tsx
  src/components/registration/SellButton.tsx
  src/components/registration/SellerAgreementCheckbox.tsx
  src/components/registration/modal/ConfirmModal.tsx
Labels: Frontend, Refactor, Feature

#148 feat: add EmptyState 컴포넌트 추가 및 물품 없을때 UI 처리
  src/components/home/AuctionSoonItemList.tsx
  src/components/home/BestItemByCategory.tsx
  src/components/home/EmptyState.tsx
  src/components/home/RealTimeRankingItem.tsx
  src/components/home/RecentAuctionList.tsx
  src/components/home/TopBidCardList.tsx
Labels: Frontend, Feature

#151 Test/searchpage
  jest.config.ts
  package.json
  src/__tests__/Searchbox.spec.tsx
  src/app/search/page.tsx
  src/components/atoms/RecentSearchWordButton.tsx
  src/components/atoms/RelatedSearchWordButton.tsx
  src/components/molecules/searchinput/RecentSearchContent.tsx
  src/components/molecules/searchinput/RelatedSearchContent.tsx
  src/components/templates/SearchBox.tsx
Labels: Frontend, Test

#156 Fix/detail
  jest.config.ts
  src/app/detail/[idx]/DetailPageClient.tsx
  src/components/detail/Bid/BidHistory.tsx
  src/types/productData.ts
Labels: Frontend, Bug Fix

#157 style: add UI 요소의 텍스트 및 스타일 수정
  src/app/page.tsx
  src/components/home/AuctionSoonList.tsx
  src/components/home/RecentAuctionList.tsx
  src/components/home/TopBidCard.tsx
  src/components/registration/SellerAgreementCheckbox.tsx
Labels: Frontend, Refactor, Feature

#165 Fix/home and route
  src/app/edit/[idx]/page.tsx
  src/components/home/TopBidCard.tsx
Labels: Frontend, Bug Fix, Refactor

#171 fix: fix type error
  src/app/detail/[idx]/page.tsx
  src/components/Header.tsx
  src/components/atoms/CategoryButton.tsx
  src/lib/api/auction.ts
Labels: Frontend, Bug Fix

#173 Fix/deploy setting
  public/favicon.ico
  src/app/detail/[idx]/DetailPageClient.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/app/search/page.tsx
Labels: Frontend, Bug Fix

#174 Develop
  public/favicon.ico
  src/app/detail/[idx]/DetailPageClient.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/app/search/page.tsx
Labels: Frontend, Chore

#176 Feature/presigned upload
  next.config.mjs
  src/app/(auth)/login/page.tsx
  src/app/edit/[idx]/page.tsx
  src/app/payment/fail/page.tsx
  src/app/registration/page.tsx
  src/components/AuctionCard.tsx
  src/components/detail/Product/AuctionImageCard.tsx
  src/components/home/AuctionSoonList.tsx
  src/components/home/BestItemByCategory.tsx
  src/components/home/RealTimeRankingItem.tsx
  src/components/home/RecentAuctionList.tsx
  src/components/home/TopBidCard.tsx
  src/components/notification/NotificationContents.tsx
  src/components/profile/MyAuctionsProductCard.tsx
  src/components/profile/MyBidsProductCard.tsx
  src/components/profile/MyPaymentsProductCard.tsx
  src/components/profile/UserProfile.tsx
  src/components/registration/ImageUploader.tsx
  src/lib/api/notification.ts
  src/lib/api/s3Upload.ts
  src/lib/api/user.ts
Labels: Frontend, Refactor, Feature

#180 Main 머지
  next.config.mjs
  src/app/detail/[idx]/page.tsx
  src/app/edit/[idx]/page.tsx
  src/app/page.tsx
  src/app/payment/page.tsx
  src/app/payment/success/page.tsx
  src/components/home/BestItemByCategory.tsx
  src/components/molecules/searchpage/CategoryDetail.tsx
  src/components/payment/Checkout.tsx
  src/components/payment/CompletedState.tsx
  src/components/profile/MyTabs.tsx
  src/components/profile/UserProfile.tsx
  src/components/registration/ImageUploader.tsx
  src/lib/api/searchboxApi.ts
  src/types/productData.ts
Labels: Frontend, Chore

#183 Test/home edit unit and e2e test
  e2e/assets/test.png
  e2e/assets/test2.jpg
  e2e/edit.spec.ts
  e2e/home.spec.ts
  e2e/registration.spec.ts
  jest.setup.ts
  src/__tests__/Edit.test.tsx
  src/__tests__/Registration.test.tsx
  src/app/registration/page.tsx
  src/components/registration/AuctionStartTimeButton.tsx
  src/components/registration/ImageUploader.tsx
  src/components/registration/SellerAgreementCheckbox.tsx
Labels: Frontend, Test

#186 feat: add registration and edit pages debounce utility
  src/app/edit/[idx]/page.tsx
  src/app/registration/page.tsx
  src/components/registration/SellButton.tsx
  src/components/registration/modal/ConfirmModal.tsx
  src/lib/util/debounce.ts
Labels: Frontend, Feature

#190 Fix/detail rerender
  src/app/detail/[idx]/DetailPageClient.tsx
  src/app/detail/[idx]/page.tsx
  src/components/detail/AuctionInfo.tsx
  src/components/detail/AuctionInfoWithBidInteraction.tsx
  src/components/detail/Bid/BidHistory.tsx
  src/components/detail/BidInteraction.tsx
  src/components/detail/DetailInfoWithBid.tsx
  src/components/detail/EditButton.tsx
  src/components/detail/ImageSlider.tsx
  src/components/detail/Product/AuctionImageCard.tsx
  src/components/detail/ProductHeader.tsx
  src/components/detail/ProductStatus.tsx
  src/components/detail/RelatedProducts.tsx
Labels: Frontend, Refactor

#195 Fix/search stream
  src/app/detail/[idx]/loading.tsx
  src/app/search/page.tsx
  src/components/wrappers/CategoryFilterWrapper.tsx
  src/components/wrappers/ProductRelatedWrapper.tsx
  src/components/wrappers/ProductResultWrapper.tsx
  src/lib/api/search.ts
Labels: Frontend, Refactor

#197 Fix/detail stream
  src/app/detail/[idx]/page.tsx
  src/app/search/page.tsx
  src/components/SearchLoading.tsx
  src/components/detail/BidInteraction.tsx
  src/components/detail/DetailInfoWithBid.tsx
  src/components/detail/Product/AuctionImageCard.tsx
  src/components/molecules/searchpage/PriceFilter.tsx
  src/components/wrappers/detail/RelatedProductsWrapper.tsx
  src/components/wrappers/search/CategoryFilterWrapper.tsx
  src/components/wrappers/search/ProductRelatedWrapper.tsx
  src/components/wrappers/search/ProductResultWrapper.tsx
  src/lib/api/auction.ts
  src/lib/api/search.ts
Labels: Frontend, Refactor, Perf

#196 Perf/home server component performance
  .gitignore
  src/app/page.tsx
  src/components/home/AuctionSoonItemList.tsx
  src/components/home/AuctionSoonList.tsx
  src/components/home/BestByCategory.tsx
  src/components/home/BestByCategoryClient.tsx
  src/components/home/DashboardStats.tsx
  src/components/home/ImageCarousel.tsx
  src/components/home/RealTimeRankingPanel.tsx
  src/components/home/RealTimeRankingPanelClient.tsx
  src/components/home/RecentAuctionList.tsx
  src/components/home/Skeleton/AuctionSoonItemListSkeleton.tsx
  src/components/home/Skeleton/BestByCategorySkeleton.tsx
  src/components/home/Skeleton/DashboardStatsSkeleton.tsx
  src/components/home/Skeleton/ImageCarouselSkeleton.tsx
  src/components/home/Skeleton/RealTimeRankingPanelSkeleton.tsx
  src/components/home/Skeleton/RecentAuctionListSkeleton.tsx
  src/components/home/Skeleton/TopBidCardListSkeleton.tsx
  src/components/home/TopBidCard.tsx
  src/components/home/TopBidCardList.tsx
  src/components/ui/skeleton.tsx
  src/lib/util/slides.ts
Labels: Frontend, Feature, Perf

#201 Feature/speedinsight
  .eslintrc.json
  next.config.mjs
  package-lock.json
  package.json
  src/app/detail/[idx]/page.tsx
  src/app/layout.tsx
  src/app/search/page.tsx
  src/components/wrappers/SearchBoxWrapper.tsx
  src/components/wrappers/detail/DetailInfoWithBidWrapper.tsx
  src/components/wrappers/search/ProductResultWrapper.tsx
Labels: Frontend, Chore

#203 fix: fix eslint & gitignore
  .gitignore
  src/app/detail/[idx]/page.tsx
  src/components/home/RecentAuctionList.tsx
  src/components/registration/SellButton.tsx
  src/lib/util/debounce.ts
Labels: Frontend, Chore

#207 메인 머지
  src/app/edit/[idx]/page.tsx
Labels: Frontend, Chore

#213 Feature/detail upgrade
  src/components/detail/AuctionInfoWithBidInteraction.tsx
  src/components/detail/BidInteraction.tsx
  src/components/detail/DetailInfoWithBid.tsx
  src/types/sse.types.ts
Labels: Frontend, Feature
