Repository goorm-369/893-front, pull requests merged in 2025-05, with the labels that each got.

#10 Feature/registrationpage
  src/app/registration/page.tsx
  src/components/registration/AuctionTitleInput.tsx
  src/components/registration/ImageUploader.tsx
  src/components/registration/PaymentInput.tsx
Labels: Frontend

#11 Feature/detailpage
  src/app/detail/[idx]/page.tsx
  src/app/layout.tsx
  src/components/detail/AuctionItemCard.tsx
  src/components/detail/ImageSlider.tsx
  src/components/detail/ProductInfo.tsx
  src/components/home/CategoryButton.tsx
Labels: Frontend

#9 Feature/homepage
  public/icons/Appliance.svg
  public/icons/Audio.svg
  public/icons/Book.svg
  public/icons/Computer.svg
  public/icons/Mobility.svg
  public/icons/Stationery.svg
  public/mocks/products.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Header.tsx
  src/components/atoms/CategoryButton.tsx
  src/components/atoms/RecentSearchWordButton.tsx
  src/components/atoms/RecommendSearchWordButton.tsx
  src/components/atoms/RelatedSearchWordButton.tsx
  src/components/atoms/SpinningWord.tsx
  src/components/home/CategoryButton.tsx
  src/components/molecules/CategorySearchSection.tsx
  src/components/molecules/HomeTitle.tsx
  src/components/molecules/SearchInput.tsx
  src/data/searchData.json
  src/types/category.ts
  tailwind.config.ts
Labels: Frontend

#18 Feature/registrationpage
  package-lock.json
  package.json
  src/app/globals.css
  src/app/registration/page.tsx
  src/components/registration/AuctionStartTimeButton.tsx
  src/components/registration/AuctionTimeButton.tsx
  src/components/registration/AuctionTitleInput.tsx
  src/components/registration/CategorySelect.tsx
  src/components/registration/DetailedInput.tsx
  src/components/registration/ImageUploader.tsx
  src/components/registration/PaymentInput.tsx
  src/components/registration/ProductStatus.tsx
  src/components/registration/SellButton.tsx
  src/components/registration/SellerAgreementCheckbox.tsx
  src/components/registration/modal/ConfirmModal.tsx
  src/components/ui/dialog.tsx
  tailwind.config.ts
Labels: Frontend

#20 Feature/search
  package-lock.json
  package.json
  src/app/globals.css
  src/app/search/page.tsx
  src/components/atoms/RelatedWordButton.tsx
  src/components/atoms/searchpage/FilterCheckBox.tsx
  src/components/atoms/searchpage/FilterRefreshButton.tsx
  src/components/atoms/searchpage/SortButton.tsx
  src/components/molecules/SearchInput.tsx
  src/components/molecules/searchpage/CategoryDetail.tsx
  src/components/molecules/searchpage/CategoryMain.tsx
  src/components/molecules/searchpage/CategorySub.tsx
  src/components/molecules/searchpage/FilterFieldSet.tsx
  src/components/molecules/searchpage/PriceFilter.tsx
  src/components/molecules/searchpage/ProductRelated.tsx
  src/components/molecules/searchpage/ProductSort.tsx
  src/components/templates/searchpage/AuctionStatusFilter.tsx
  src/components/templates/searchpage/CategoryFilter.tsx
  src/components/templates/searchpage/ProductStatusFilter.tsx
  src/components/ui/select.tsx
Labels: Frontend

#22 chore: update package-lock.json
  package-lock.json
Labels: Hot Fix

#23 Feature/detailpage
  src/components/detail/AuctionItemCard.tsx
  src/components/detail/ProductInfo.tsx
  src/components/detail/WarningModal.tsx
Labels: Frontend, Feature

#24 chore: update package-lock.json
  package-lock.json
Labels: Hot Fix

#29 Feature/notificationpage
  .husky/_/commit-msg
  .husky/_/pre-commit
  public/images/신짱구.png
  src/components/Header.tsx
  src/components/notification/NotificationContents.tsx
  src/components/notification/NotificationDropdown.tsx
  tsconfig.json
Labels: Frontend, Feature

#31 feat: 배송지 추가 및 삭제기능
  package-lock.json
  package.json
  src/components/profile/Address/AddressModal.tsx
  src/components/profile/Address/DaumPostcodeEmbed.tsx
  src/components/profile/Address/DaumPostcodeModal.tsx
  src/components/profile/Address/DeliveryAddressCard.tsx
  src/components/profile/UserProfile.tsx
Labels: Frontend, Feature

#34 Feature/editpage
  src/app/edit/page.tsx
  src/app/registration/page.tsx
  src/components/registration/AuctionStartTimeButton.tsx
  src/components/registration/AuctionTimeButton.tsx
  src/components/registration/AuctionTitleInput.tsx
  src/components/registration/CategorySelect.tsx
  src/components/registration/ImageUploader.tsx
  src/components/registration/ProductStatus.tsx
  src/components/registration/SellButton.tsx
  src/components/registration/constants/productConditions.ts
Labels: Frontend, Feature

#36 Feature/notificationpage
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/app/fcmtest/page.tsx
  src/components/Header.tsx
  src/components/TestFCM.tsx
  src/components/notification/NotificationContents.tsx
  src/components/notification/NotificationDropdown.tsx
  src/lib/firebase-messaging.ts
Labels: Frontend, Refactor, Feature

#35 Feature/profile
  src/components/profile/UserProfile.tsx
Labels: Frontend, Refactor, Feature

#37 Feature/bidlog
  src/app/buyer/detail/[idx]/page.tsx
  src/app/detail/[idx]/page.tsx
  src/app/seller/detail/[idx]/page.tsx
  src/components/detail/AuctionItemCard.tsx
  src/components/detail/AuctionState.tsx
  src/components/detail/BidHistory.tsx
  src/components/detail/BidInteraction.tsx
  src/components/detail/ImageSlider.tsx
  src/components/detail/ProductCard.tsx
  src/components/detail/ProductHeader.tsx
  src/components/detail/ProductInfo.tsx
  src/components/detail/SellerProductHeader.tsx
  src/components/detail/SellerProductInfo.tsx
  src/data/productData.ts
Labels: Frontend, Refactor, Feature

#42 Feature/bidhistory
  src/app/buyer/detail/[idx]/page.tsx
  src/app/page.tsx
  src/app/seller/detail/[idx]/page.tsx
  src/components/detail/AuctionState.tsx
  src/components/detail/Bid/BidHistory.tsx
  src/components/detail/Bid/BidInteraction.tsx
  src/components/detail/GoodsInfo.tsx
  src/components/detail/ImageSlider.tsx
  src/components/detail/Product/AuctionItemCard.tsx
  src/components/detail/Product/BUY/BuyerDetailView.tsx
  src/components/detail/Product/BUY/ProductHeader.tsx
  src/components/detail/Product/BUY/ProductInfo.tsx
  src/components/detail/Product/GoodsInfo.tsx
  src/components/detail/Product/ProductCard.tsx
  src/components/detail/Product/Sell/SellerDetailView.tsx
  src/components/detail/Product/Sell/SellerProductHeader.tsx
  src/components/detail/Product/Sell/SellerProductInfo.tsx
  src/components/detail/ProductCard.tsx
  src/components/detail/SellerProductInfo.tsx
  src/data/productData.ts
  src/types/productData.ts
Labels: Frontend, Feature

#47 Feature/searchapi
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/QueryProvider.tsx
  src/components/atoms/RecentSearchWordButton.tsx
  src/components/atoms/RelatedSearchWordButton.tsx
  src/components/atoms/searchpage/FilterRefreshButton.tsx
  src/components/detail/Product/ProductCard.tsx
  src/components/molecules/searchinput/RecentSearchContent.tsx
  src/components/molecules/searchinput/RelatedSearchContent.tsx
  src/components/molecules/searchpage/CategoryDetail.tsx
  src/components/molecules/searchpage/CategoryMain.tsx
  src/components/molecules/searchpage/CategorySub.tsx
  src/components/molecules/searchpage/PriceFilter.tsx
  src/components/molecules/searchpage/ProductSort.tsx
  src/components/templates/SearchInput.tsx
  src/components/templates/searchpage/AuctionStatusFilter.tsx
  src/components/templates/searchpage/ProductStatusFilter.tsx
  src/lib/api/search.ts
  src/lib/api/searchbox.ts
  src/types/response.types.ts
Labels: Frontend, Feature

#48 Hotfix/searchapi
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/detail/Product/AuctionCard.tsx
  src/components/detail/Product/BUY/BuyerDetailView.tsx
  src/components/detail/Product/Sell/SellerDetailView.tsx
  src/components/molecules/searchinput/RecentSearchContent.tsx
  src/components/molecules/searchinput/RelatedSearchContent.tsx
  src/components/molecules/searchpage/ProductRelated.tsx
Labels: Frontend, Bug Fix

#49 Feature/edit
  src/app/edit/page.tsx
  src/app/page.tsx
  src/app/registration/page.tsx
  src/app/search/page.tsx
  src/components/Header.tsx
  src/components/registration/AuctionStartTimeButton.tsx
  src/components/registration/AuctionTimeButton.tsx
  src/components/registration/ImageUploader.tsx
  src/components/registration/PaymentInput.tsx
  src/components/registration/constants/productConditions.ts
  src/middleware.ts
Labels: Frontend, Bug Fix, Refactor, Feature

#51 fix: add try catch
  src/lib/api/search.ts
Labels: Frontend, Bug Fix

#53 fix: revert edit page
  src/app/edit/page.tsx
  src/app/registration/page.tsx
  src/components/registration/AuctionStartTimeButton.tsx
  src/components/registration/AuctionTimeButton.tsx
  src/components/registration/ImageUploader.tsx
  src/components/registration/PaymentInput.tsx
  src/components/registration/constants/productConditions.ts
Labels: Frontend, Feature

#54 Feature/routing
  src/lib/api/auction.ts
Labels: Frontend, Bug Fix

#55 feat: 수정하기라우팅 설정
  src/app/edit/[idx]/page.tsx
  src/components/detail/Product/Sell/SellerProductHeader.tsx
  src/components/detail/Product/Sell/SellerProductInfo.tsx
Labels: Frontend, Feature

#56 Feature/maypageapi
  src/components/profile/Address/AddressModal.tsx
  src/components/profile/Address/DaumPostcodeModal.tsx
  src/components/profile/Address/DeliveryAddressCard.tsx
  src/components/profile/UserProfile.tsx
  src/lib/api/user.ts
  src/types/userData.ts
Labels: Frontend, Bug Fix, Feature

#57 Feature/notificationpage
  src/app/globals.css
  src/app/layout.tsx
  src/app/search/page.tsx
  src/components/GlobalFCMSetup.tsx
  src/components/Header.tsx
  src/components/notification/NotificationDropdown.tsx
  src/lib/api/notification.ts
  src/lib/api/search.ts
  src/lib/axios.ts
  src/lib/firebase-messaging.ts
Labels: Frontend, Refactor, Feature

#59 Feature/tosspay
  next.config.mjs
  package-lock.json
  package.json
  src/app/globals.css
  src/app/payment/fail/page.tsx
  src/app/payment/page.tsx
  src/app/payment/success/page.tsx
  src/components/detail/ImageSlider.tsx
  src/components/payment/Checkout.tsx
  src/components/payment/CompletedState.tsx
  src/components/payment/FinalPaymentSummary.tsx
  src/components/payment/LoadingState.tsx
  src/components/payment/PaySuccess.tsx
  src/components/payment/ShippingInfo.tsx
  src/components/ui/separator.tsx
  src/lib/api/order.ts
  src/lib/api/payment.ts
  src/lib/api/searchbox.ts
  src/types/payment.types.ts
  src/types/response.types.ts
Labels: Frontend, Feature

#60 Feature/relateditem
  src/components/detail/Product/BUY/BuyerDetailView.tsx
  src/components/detail/Product/GoodsInfo.tsx
  src/components/detail/Product/RelatedItemCard.tsx
  src/components/detail/Product/Sell/SellerDetailView.tsx
  src/data/dummyBidData.json
  src/data/dummyProductData.ts
  src/lib/api/auction.ts
  src/types/productData.ts
Labels: Frontend, Bug Fix, Refactor, Feature

#63 feature/fixdetail
  src/components/detail/ImageSlider.tsx
  src/components/detail/Product/AuctionItemCard.tsx
  src/components/detail/Product/BUY/BuyerDetailView.tsx
  src/components/detail/Product/Sell/SellerDetailView.tsx
Labels: Frontend, Bug Fix

#70 Fix/registration and edit
  src/app/edit/[idx]/page.tsx
  src/app/registration/page.tsx
  src/components/registration/CategorySelect.tsx
  src/components/registration/ImageUploader.tsx
  src/components/registration/PaymentInput.tsx
Labels: Frontend, Bug Fix, Refactor

#76 Fix/payment
  package-lock.json
  package.json
  public/icons/SearchEmpty.svg
  src/app/page.tsx
  src/app/payment/page.tsx
  src/app/payment/success/page.tsx
  src/app/search/page.tsx
  src/components/detail/Product/AuctionCard.tsx
  src/components/molecules/CategorySearchSection.tsx
  src/components/molecules/searchinput/RelatedSearchContent.tsx
  src/components/molecules/searchpage/CategoryDetail.tsx
  src/components/molecules/searchpage/CategoryMain.tsx
  src/components/molecules/searchpage/CategorySub.tsx
  src/components/molecules/searchpage/PriceFilter.tsx
  src/components/molecules/searchpage/SearchPagination.tsx
  src/components/payment/Checkout.tsx
  src/components/payment/PaySuccess.tsx
  src/components/payment/ShippingInfo.tsx
  src/components/templates/searchpage/AuctionStatusFilter.tsx
  src/components/templates/searchpage/CategoryFilter.tsx
  src/components/templates/searchpage/ProductStatusFilter.tsx
  src/components/ui/pagination.tsx
  src/lib/api/order.ts
  src/lib/api/payment.ts
  src/lib/api/search.ts
  src/types/category.ts
  src/types/payment.types.ts
  src/types/response.types.ts
Labels: Frontend, Bug Fix, Feature

#81 feat: 추가된 오류 및 접근 페이지 구현
  src/app/(auth)/forbidden/page.tsx
  src/app/(auth)/unauthorized/page.tsx
  src/app/error.tsx
  src/app/global-error.tsx
  src/app/not-found.tsx
Labels: Frontend, Feature

#78 Fix/ Notification 디버깅 로그 제거 및 오류 처리 시 사용자 알림 추가
  src/components/notification/NotificationContents.tsx
  src/components/notification/NotificationDropdown.tsx
Labels: Frontend, Bug Fix

#82 Feature/canclebid
  src/app/detail/[idx]/page.tsx
  src/components/detail/Bid/BidInteraction.tsx
  src/components/detail/Product/BUY/ProductInfo.tsx
  src/lib/api/auction.ts
  src/types/productData.ts
Labels: Frontend, Bug Fix, Refactor

#85 Feature/deleteauction
  src/components/profile/MyAuctionsProductCard.tsx
  src/lib/api/auction.ts
Labels: Frontend, Feature

#87 Feature/editcomponent
  src/app/detail/[idx]/page.tsx
  src/components/detail/Bid/BidHistory.tsx
  src/components/detail/Bid/BidInteraction.tsx
  src/components/detail/Product/GoodsInfo.tsx
  src/components/profile/MyAuctionsProductCard.tsx
  src/components/profile/MyBidsProductCard.tsx
  src/components/profile/MyScrapsProductCard.tsx
  src/components/profile/UserProfile.tsx
Labels: Frontend, Refactor

#83 Fix/payment
  src/app/payment/page.tsx
  src/app/search/page.tsx
  src/components/atoms/searchpage/PriceRangeSlider.tsx
  src/components/molecules/searchpage/CategoryDetail.tsx
  src/components/molecules/searchpage/CategoryMain.tsx
  src/components/molecules/searchpage/CategorySub.tsx
  src/components/molecules/searchpage/PriceFilter.tsx
  src/components/payment/Checkout.tsx
  src/components/payment/CompletedState.tsx
  src/components/payment/PaySuccess.tsx
  src/components/templates/SearchInput.tsx
  src/components/templates/searchpage/CategoryFilter.tsx
  src/lib/api/order.ts
  src/lib/api/search.ts
  src/lib/api/searchbox.ts
  src/types/payment.types.ts
  src/types/productData.ts
  src/types/response.types.ts
Labels: Frontend, Bug Fix

#91 Feature/fixbid 입찰 시 생기는 버그 수정
  src/app/detail/[idx]/page.tsx
  src/components/detail/Bid/BidInteraction.tsx
Labels: Frontend, Bug Fix

#93 Refactor/registration and edit
  src/app/edit/[idx]/page.tsx
  src/app/registration/page.tsx
  src/components/registration/CategorySelect.tsx
  src/components/registration/DetailedInput.tsx
  src/components/registration/ProductStatus.tsx
Labels: Frontend, Refactor

#104 fix: add accesstoken
  src/app/page.tsx
Labels: Frontend, Bug Fix

#105 Refactor/paymentinput
  src/components/registration/PaymentInput.tsx
Labels: Frontend, Refactor, Feature

#114 refactor: 정렬 및 주석 수정, Swiper 진행 바 스타일 추가
  src/app/globals.css
  src/app/page.tsx
  src/components/home/ImageCarousel.tsx
Labels: Frontend, Refactor

#116 feat: add recentauctionList component
  src/app/page.tsx
  src/components/home/RecentAuctionList.tsx
Labels: Frontend, Feature

#117 Feature/realtime rank
  src/app/page.tsx
  src/components/home/ImageCarousel.tsx
  src/components/home/RealTimeRankingItem.tsx
Labels: Frontend, Feature

#112 Fix/detailpage
  src/app/detail/[idx]/DetailPageClient.tsx
  src/app/detail/[idx]/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/AuctionCard.tsx
  src/components/Header.tsx
  src/components/atoms/RecentSearchWordButton.tsx
  src/components/detail/AuctionInfo.tsx
  src/components/detail/AuctionState.tsx
  src/components/detail/Bid/BidInteraction.tsx
  src/components/detail/BidInteraction.tsx
  src/components/detail/ImageSlider.tsx
  src/components/detail/Product/AuctionImageCard.tsx
  src/components/detail/Product/BUY/ProductHeader.tsx
  src/components/detail/Product/BUY/ProductInfo.tsx
  src/components/detail/Product/GoodsInfo.tsx
  src/components/detail/Product/RelatedItemCard.tsx
  src/components/detail/Product/Sell/SellerProductHeader.tsx
  src/components/detail/Product/Sell/SellerProductInfo.tsx
  src/components/detail/ProductHeader.tsx
  src/components/detail/WarningModal.tsx
  src/components/molecules/searchpage/PriceFilter.tsx
  src/components/payment/Checkout.tsx
  src/components/profile/MyPaymentsProductCard.tsx
  src/components/templates/SearchBox.tsx
  src/components/templates/searchpage/ProductStatusFilter.tsx
  src/hooks/useScarp.ts
  src/hooks/useSearchBox.ts
  src/lib/api/auction.ts
  src/lib/api/searchboxApi.ts
  src/lib/util/detailpage.ts
  src/types/productData.ts
Labels: Frontend, Bug Fix, Refactor

#126 Feature/weekly topprice
  src/app/page.tsx
  src/components/home/DashboardStats.tsx.tsx
  src/components/home/TopBodCard.tsx
  src/lib/util/priceUtils.ts
Labels: Frontend, Feature

#130 Fix/paymentpage
  src/app/layout.tsx
  src/app/payment/page.tsx
  src/app/payment/success/loading.tsx
  src/app/payment/success/page.tsx
  src/components/AuctionCard.tsx
  src/components/payment/CompletedState.tsx
  src/components/payment/FinalPaymentSummary.tsx
  src/components/payment/PaySuccess.tsx
  src/components/payment/PaymentMehodSelector.tsx
  src/components/payment/ShippingInfo.tsx
  src/components/profile/Address/DeliveryAddressCard.tsx
  src/components/profile/MyTabs.tsx
  src/components/profile/UserProfile.tsx
  src/components/ui/LoadingSpinner.tsx
  src/lib/api/order.ts
  src/types/productData.ts
  src/types/response.types.ts
Labels: Frontend, Bug Fix, Refactor

#135 Fix/change to toast
  src/app/edit/[idx]/page.tsx
  src/app/layout.tsx
  src/app/registration/page.tsx
  src/components/TestFCM.tsx
  src/components/molecules/searchpage/PriceFilter.tsx
  src/components/notification/NotificationContents.tsx
  src/components/notification/NotificationDropdown.tsx
  src/components/payment/Checkout.tsx
  src/components/profile/MyAuctionsProductCard.tsx
  src/components/registration/AuctionTimeButton.tsx
  src/components/registration/ImageUploader.tsx
  src/components/templates/SearchBox.tsx
Labels: Frontend, Refactor

#139 fix: add TopBidItem 인터페이스에서 isCurrentUserBuyer를 buyer로 변경 및 API 호출 경로 수정
  src/components/home/TopBidCard.tsx
  src/components/home/TopBidCardList.tsx
  src/lib/api/home.ts
Labels: Frontend, Feature, Hot Fix
